name: flutter_horizontal_vertical_tabview
description: A horizontal & vertical tab widget for flutter.
version: 0.0.1
homepage: https://github.com/wangeguo/flutter_horizontal_vertical_tabview

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true